In [1]:
import numpy as np

In [2]:
#linspace
vec4=np.linspace(0,5,10)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [3]:
#reshape
print(vec4.reshape(5,2))

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [4]:
print(vec4.reshape(2,5))

[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]


In [5]:
print(vec4.reshape(10,1))

[[0.        ]
 [0.55555556]
 [1.11111111]
 [1.66666667]
 [2.22222222]
 [2.77777778]
 [3.33333333]
 [3.88888889]
 [4.44444444]
 [5.        ]]


In [6]:
mat=np.zeros([5,3])
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
mat3=np.ones([3,5])
print(mat3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
mat4=np.eye(4)
print(mat4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
vec5=np.arange(1,6)
vec6=np.arange(3,8)
print(vec5+vec6)

[ 4  6  8 10 12]


In [11]:
print(vec5-vec6)

[-2 -2 -2 -2 -2]


In [12]:
m1=np.array([[1,2],[3,4]])
print(m1)

[[1 2]
 [3 4]]


In [13]:
m2=np.array([[1,1],[4,5]])
print(m2)

[[1 1]
 [4 5]]


In [14]:
print(m1+m2)

[[2 3]
 [7 9]]


In [15]:
print(m1-m2)

[[ 0  1]
 [-1 -1]]


In [16]:
print(m1*m2) #no. of col of 1st matrix shld match the no. of rows of 2nd metrix

[[ 1  2]
 [12 20]]


In [17]:
print(np.matmul(m1,m2))

[[ 9 11]
 [19 23]]


In [18]:
vec7=np.array(['red','blue','orange','pink','red'])

In [19]:
print(np.unique(vec7))

['blue' 'orange' 'pink' 'red']


In [21]:
rand_mat=np.random.rand(3,5)
print(rand_mat)

[[0.94158225 0.73971055 0.58316672 0.3130949  0.34681377]
 [0.67928673 0.3922775  0.62679106 0.0121751  0.1336471 ]
 [0.89771916 0.26609732 0.72049484 0.89532663 0.81725583]]


In [22]:
rand_mat=np.random.randn(3,5) #randn includes -ve variables also
print(rand_mat)

[[-1.02089184  1.6653279  -0.69834608 -1.36306331  0.64002699]
 [-1.06308961 -0.68480075 -0.73424264 -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [23]:
#access
rand_vec=np.random.randn(19)
print(rand_vec)

[-1.51285722 -0.29220796 -0.22932553 -2.4213887   0.5530303  -0.19456788
 -0.60639408  0.80525859 -1.20539865 -0.25948743 -1.60747581 -0.76591304
 -1.44533399 -0.22194407  0.98052636 -0.65389218 -0.50617    -1.34465261
 -0.7373664 ]


In [24]:
print(rand_vec[0])

-1.5128572246975704


In [25]:
print(rand_vec[-1])

-0.7373663971168477


In [27]:
print(rand_vec[0:8:2])

[-1.51285722 -0.22932553  0.5530303  -0.60639408]


In [28]:
print(rand_mat)

[[-1.02089184  1.6653279  -0.69834608 -1.36306331  0.64002699]
 [-1.06308961 -0.68480075 -0.73424264 -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [29]:
print(rand_mat[0,0])

-1.0208918404072451


In [31]:
print(rand_mat[[0],[0]])

[-1.02089184]


In [32]:
print(rand_mat[0:2,1:3])

[[ 1.6653279  -0.69834608]
 [-0.68480075 -0.73424264]]


In [33]:
print(rand_vec)

[-1.51285722 -0.29220796 -0.22932553 -2.4213887   0.5530303  -0.19456788
 -0.60639408  0.80525859 -1.20539865 -0.25948743 -1.60747581 -0.76591304
 -1.44533399 -0.22194407  0.98052636 -0.65389218 -0.50617    -1.34465261
 -0.7373664 ]


In [34]:
print(rand_vec[np.arange(0,15,3)])

[-1.51285722 -2.4213887  -0.60639408 -0.25948743 -1.44533399]


In [35]:
rand_vec[3:5]=4
print(rand_vec)

[-1.51285722 -0.29220796 -0.22932553  4.          4.         -0.19456788
 -0.60639408  0.80525859 -1.20539865 -0.25948743 -1.60747581 -0.76591304
 -1.44533399 -0.22194407  0.98052636 -0.65389218 -0.50617    -1.34465261
 -0.7373664 ]


In [36]:
rand_vec[3:5]=[3,4]
print(rand_vec)

[-1.51285722 -0.29220796 -0.22932553  3.          4.         -0.19456788
 -0.60639408  0.80525859 -1.20539865 -0.25948743 -1.60747581 -0.76591304
 -1.44533399 -0.22194407  0.98052636 -0.65389218 -0.50617    -1.34465261
 -0.7373664 ]


In [41]:
print(rand_mat)

[[-1.02089184  1.6653279  -0.69834608 -1.36306331  0.64002699]
 [-1.06308961 -0.68480075 -0.73424264 -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [42]:
sub_mat=rand_mat[0:2,0:3]

In [43]:
print(sub_mat)

[[-1.02089184  1.6653279  -0.69834608]
 [-1.06308961 -0.68480075 -0.73424264]]


In [44]:
sub_mat[:]=3
print(sub_mat)

[[3. 3. 3.]
 [3. 3. 3.]]


In [45]:
print(rand_mat) #if we make changes in submetrix they will occure in original metrix 

[[ 3.          3.          3.         -1.36306331  0.64002699]
 [ 3.          3.          3.         -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [46]:
sub_mat1=rand_mat[0:2,0:2].copy() #copy() 

In [47]:
sub_mat1[:]=4

In [48]:
print(rand_mat)

[[ 3.          3.          3.         -1.36306331  0.64002699]
 [ 3.          3.          3.         -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [49]:
#Logical indexing

In [51]:
random_vec=np.random.rand(15)

In [52]:
print(rand_vec>0)

[False False False  True  True False False  True False False False False
 False False  True False False False False]


In [53]:
print(random_vec[random_vec>0])

[0.58491262 0.25699518 0.53119896 0.70305682 0.85943081 0.37827544
 0.27815921 0.4171237  0.11043227 0.55482039 0.62316914 0.40487578
 0.67468385 0.07536893 0.6920881 ]


In [54]:
print(rand_mat[rand_mat>0])

[3.         3.         3.         0.64002699 3.         3.
 3.         0.28245092 0.18025209 0.87330058]


In [55]:
np.save('sample_mat',rand_mat)

In [56]:
np.savez('sample_matrices',f1=rand_mat,f2=rand_vec)

In [58]:
data1=np.load('sample_mat.npy')

In [59]:
print(data1)

[[ 3.          3.          3.         -1.36306331  0.64002699]
 [ 3.          3.          3.         -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [60]:
data2=np.load('sample_matrices.npz')

In [61]:
print(data2['f1'])

[[ 3.          3.          3.         -1.36306331  0.64002699]
 [ 3.          3.          3.         -0.36911896  0.28245092]
 [-0.23934999  0.18025209  0.87330058 -0.16883714 -1.56281166]]


In [62]:
print(data2['f2'])

[-1.51285722 -0.29220796 -0.22932553  3.          4.         -0.19456788
 -0.60639408  0.80525859 -1.20539865 -0.25948743 -1.60747581 -0.76591304
 -1.44533399 -0.22194407  0.98052636 -0.65389218 -0.50617    -1.34465261
 -0.7373664 ]
