In [1]:
#Numpy
#mathematical computations
#generate random variables
#vector,matrix,tensors-----array

In [2]:
#scalar= a data which has one row one column
#vector= a data which has one row multiple col or multiple rows and one col
#metrix= a data which has multiple rows with multiple column
#tensor= a data which has more than a row and a column

In [3]:
import numpy

In [4]:
import numpy as np #renaming numpy as np (not mandatory)

In [5]:
print(np.cos(np.pi))

-1.0


In [6]:
print(np.sqrt(121))

11.0


In [7]:
#create numpy arrays
#from List
#creating vector from List
vec=np.array([1,2,3,4])

In [8]:
type(vec)

numpy.ndarray

In [9]:
print(vec)

[1 2 3 4]


In [10]:
#create a metrix from List
mat=np.array([[1,2,3],[11,23,4],[1,2,4]])

In [11]:
type(mat)

numpy.ndarray

In [12]:
print(mat)

[[ 1  2  3]
 [11 23  4]
 [ 1  2  4]]


In [13]:
#Transpose of matrix:
#interchanging the rows and columns
print(mat.T)

[[ 1 11  1]
 [ 2 23  2]
 [ 3  4  4]]


In [14]:
#Creating array using arange
vec2=np.arange(0,15)
type(vec2)

numpy.ndarray

In [15]:
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
vec3=np.arange(3,21,6) #[3 3+6 9+6]
print(vec3)

[ 3  9 15]


In [17]:
#creating array using linspace----Linearly spaced vector
vec4=np.linspace(0,5,10) #creates equal spaced 10 elements btwn 0 to 5
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [18]:
#Reshaping techniques
#number of elements should be same
print(vec4.reshape(5,2))

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [19]:
print(vec4) #no change to original data

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [20]:
print(vec4.reshape(10,1))

[[0.        ]
 [0.55555556]
 [1.11111111]
 [1.66666667]
 [2.22222222]
 [2.77777778]
 [3.33333333]
 [3.88888889]
 [4.44444444]
 [5.        ]]


In [21]:
mat2=np.zeros([3,5])

In [22]:
print(mat2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
mat3=np.ones([3,5])

In [24]:
print(mat3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
mat4=np.eye(3)
print(mat4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#Linear algebra
vec5=np.arange(1,6)
vec6=np.arange(3,8)

In [27]:
print(vec5)
print(vec6)

[1 2 3 4 5]
[3 4 5 6 7]


In [28]:
print(vec5+vec6)

[ 4  6  8 10 12]


In [29]:
print(vec5-vec6)

[-2 -2 -2 -2 -2]


In [30]:
print(vec5*vec6)

[ 3  8 15 24 35]


In [31]:
print(1/vec5)

[1.         0.5        0.33333333 0.25       0.2       ]


In [32]:
print(np.sqrt(vec5))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [33]:
A=np.array([[1,2],[3,4]]) #new question
B=np.array([[5,1],[2,4]])

In [34]:
print(A)

[[1 2]
 [3 4]]


In [35]:
print(B)

[[5 1]
 [2 4]]


In [36]:
print(A+B)

[[6 3]
 [5 8]]


In [37]:
print(A-B)

[[-4  1]
 [ 1  0]]


In [38]:
print(A*B)

[[ 5  2]
 [ 6 16]]


In [39]:
print(np.matmul(A,B)) #MATRIX MULTIPLICATION (np.matmul)

[[ 9  9]
 [23 19]]


In [40]:
vec7=np.array(['blue','red','blue','red','yellow','brown'])

In [41]:
print(np.unique(vec7))

['blue' 'brown' 'red' 'yellow']


In [42]:
#generate random samples
rand_mat=np.random.rand(5,5)

In [43]:
print(rand_mat)

[[0.85203149 0.9404264  0.70866073 0.90661701 0.66838271]
 [0.11007815 0.11945082 0.97724016 0.89843611 0.53220481]
 [0.06199885 0.06159279 0.53667769 0.62400271 0.19629243]
 [0.36201251 0.53510313 0.99652258 0.28919919 0.43016034]
 [0.20951686 0.06213652 0.00651283 0.28260045 0.81466779]]


In [44]:
rand_mat2=np.random.randn(2,3) #values follow normal distribution

In [45]:
print(rand_mat2)

[[ 0.05601833  0.51360496  0.55817412]
 [-0.55196964  0.08667594 -0.09123988]]


In [46]:
#mean of ele
print(np.mean(rand_mat))

0.48730100237943136


In [47]:
#standared deviation
print(np.std(rand_mat))

0.32927458144806765


In [48]:
#min element (smallest element)
print(np.min(rand_mat))

0.0065128273103489676


In [49]:
#max element 
print(np.max(rand_mat))

0.9965225839770315


In [50]:
#Access elements from array
rand_vec=np.random.randn(19)
print(rand_vec)

[ 0.24767605 -1.06717527  0.11201716 -0.31821117 -0.22811226  0.09273749
 -0.95480279 -0.87887632  0.15314413  0.62553853 -0.46369252  2.14927256
  0.97279669  0.4789785   0.01788179  1.00620476 -2.21421509 -0.21437482
 -0.3311392 ]


In [51]:
print(rand_vec[0])

0.2476760460420379


In [52]:
print(rand_vec[18])

-0.3311392041966827


In [53]:
print(rand_vec[-1])

-0.3311392041966827


In [54]:
print(rand_vec[-2])

-0.2143748158360052


In [55]:
rand_vec[0]=100
print(rand_vec)

[ 1.00000000e+02 -1.06717527e+00  1.12017162e-01 -3.18211172e-01
 -2.28112258e-01  9.27374882e-02 -9.54802787e-01 -8.78876322e-01
  1.53144134e-01  6.25538531e-01 -4.63692523e-01  2.14927256e+00
  9.72796686e-01  4.78978496e-01  1.78817917e-02  1.00620476e+00
 -2.21421509e+00 -2.14374816e-01 -3.31139204e-01]


In [56]:
print(rand_vec[0:5])

[100.          -1.06717527   0.11201716  -0.31821117  -0.22811226]


In [57]:
print(rand_vec[0:5:2])

[100.           0.11201716  -0.22811226]


In [58]:
print(rand_vec[np.arange(0,6,2)])

[100.           0.11201716  -0.22811226]


In [59]:
s=np.arange(0,6,2)
print(s)

[0 2 4]


In [60]:
print(rand_vec[s])

[100.           0.11201716  -0.22811226]
